version: "3.8"

services:
  installer:
    image: openjdk:11-slim-buster
    container_name: pega-installer
    command: ["./install-pega.sh"]
    volumes:
      - ./distr:/distr
      - ./application/postgresql-42.2.14.jar:/postgresql-42.2.14.jar
      - ./installer/install-pega.sh:/install-pega.sh
    depends_on:
      database:
        condition: service_healthy

  database:
    build: ./database
    image: pega-easy-install-database
    container_name: pega-database
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 10s
      retries: 120
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose: 
      - 5432
    ports: 
      - "5432:5432"
    volumes:
      - database-logs:/logs:rw

  application:
    build: ./application
    image: pega-easy-install-application
    container_name: pega-application
    environment: 
      - JDBC_URL=jdbc:postgresql://database:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - JAVA_OPTS=-Dpega.logdir=/usr/local/tomcat/logs/pega_logs
    ports: 
      - "8080:8080"
      - "8000:8000"
    volumes:
      - application-logs:/usr/local/tomcat/logs/pega_logs:rw
    depends_on:
      database:
        condition: service_healthy
  
  web-tail:
    build: ./web-tail
    image: pega-easy-install-logs
    container_name: pega-logs
    ports: 
      - "4444:4444"
    volumes:
      - application-logs:/usr/src/app/pega_logs
      - database-logs:/usr/src/app/database_logs

volumes:
  application-logs:
  database-logs:
